### ISSUE TITLE
OpenAudioMc - Web Client on a dedicated server ! No Link with Server

### ISSUE THREAD

**Issue by Rouchesta** [Mindgamesnl/OpenAudioMc#88]
OpenAudioMC 4.0
Spigot 1.12.2

Description :
When i try to clic on the link to open client side it says : 
**Oh no! :( life has its ups and downs, we could not connect or lost connection to the minecraft server! no need to panic, try again later.**

Config : 
```
############################################################
# +------------------------------------------------------+ #
# |                    Web Client                        | #
# |         Configuration for your web client!           | #
# |       (can be disabled by using '-' as value)        | #
# +------------------------------------------------------+ #
############################################################
web:
  url: 'http://audio.teamkog.com/'
  title: 'Kogcraft'
  background: '-'
  startsound: '-'
  ambiancesound: '-'
  speaker_radius: 10
```

Is there a step by step tutorial to know how to configure my hosted web client with Openaudio ?

Thank you.
Gaëtan.
